temp fix

diff --git a/.github/workflows/builder.yml b/.github/workflows/builder.yml
--- a/.github/workflows/builder.yml
+++ b/.github/workflows/builder.yml
@@ -337,112 +337,112 @@ jobs:
       #     password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Login to GitHub Container Registry
-        if: matrix.registry == 'ghcr.io/home-assistant'
+        if: matrix.registry == 'ghcr.io/my-smart-homes'
         uses: docker/login-action@v3.3.0
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build Meta Image
-        shell: bash
-        run: |
-          export DOCKER_CLI_EXPERIMENTAL=enabled
+      # - name: Build Meta Image
+      #   shell: bash
+      #   run: |
+      #     export DOCKER_CLI_EXPERIMENTAL=enabled
 
-          function create_manifest() {
-            local tag_l=${1}
-            local tag_r=${2}
-            local registry=${{ matrix.registry }}
+      #     function create_manifest() {
+      #       local tag_l=${1}
+      #       local tag_r=${2}
+      #       local registry=${{ matrix.registry }}
 
-            docker manifest create "${registry}/home-assistant:${tag_l}" \
-              "${registry}/amd64-homeassistant:${tag_r}" \
-              "${registry}/i386-homeassistant:${tag_r}" \
-              "${registry}/armhf-homeassistant:${tag_r}" \
-              "${registry}/armv7-homeassistant:${tag_r}" \
-              "${registry}/aarch64-homeassistant:${tag_r}"
+      #       docker manifest create "${registry}/my-smart-homes:${tag_l}" \
+      #         "${registry}/amd64-homeassistant:${tag_r}" \
+      #         "${registry}/i386-homeassistant:${tag_r}" \
+      #         "${registry}/armhf-homeassistant:${tag_r}" \
+      #         "${registry}/armv7-homeassistant:${tag_r}" \
+      #         "${registry}/aarch64-homeassistant:${tag_r}"
 
-            docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-              "${registry}/amd64-homeassistant:${tag_r}" \
-              --os linux --arch amd64
+      #       docker manifest annotate "${registry}/my-smart-homes:${tag_l}" \
+      #         "${registry}/amd64-homeassistant:${tag_r}" \
+      #         --os linux --arch amd64
 
-            docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-              "${registry}/i386-homeassistant:${tag_r}" \
-              --os linux --arch 386
+      #       docker manifest annotate "${registry}/my-smart-homes:${tag_l}" \
+      #         "${registry}/i386-homeassistant:${tag_r}" \
+      #         --os linux --arch 386
 
-            docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-              "${registry}/armhf-homeassistant:${tag_r}" \
-              --os linux --arch arm --variant=v6
+      #       docker manifest annotate "${registry}/my-smart-homes:${tag_l}" \
+      #         "${registry}/armhf-homeassistant:${tag_r}" \
+      #         --os linux --arch arm --variant=v6
 
-            docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-              "${registry}/armv7-homeassistant:${tag_r}" \
-              --os linux --arch arm --variant=v7
+      #       docker manifest annotate "${registry}/my-smart-homes:${tag_l}" \
+      #         "${registry}/armv7-homeassistant:${tag_r}" \
+      #         --os linux --arch arm --variant=v7
 
-            docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-              "${registry}/aarch64-homeassistant:${tag_r}" \
-              --os linux --arch arm64 --variant=v8
+      #       docker manifest annotate "${registry}/my-smart-homes:${tag_l}" \
+      #         "${registry}/aarch64-homeassistant:${tag_r}" \
+      #         --os linux --arch arm64 --variant=v8
 
-            docker manifest push --purge "${registry}/home-assistant:${tag_l}"
-            cosign sign --yes "${registry}/home-assistant:${tag_l}"
-          }
+      #       docker manifest push --purge "${registry}/my-smart-homes:${tag_l}"
+      #       cosign sign --yes "${registry}/my-smart-homes:${tag_l}"
+      #     }
 
-          function validate_image() {
-            local image=${1}
-            if ! cosign verify --certificate-oidc-issuer https://token.actions.githubusercontent.com --certificate-identity-regexp https://github.com/home-assistant/core/.* "${image}"; then
-              echo "Invalid signature!"
-              exit 1
-            fi
-          }
+      #     function validate_image() {
+      #       local image=${1}
+      #       if ! cosign verify --certificate-oidc-issuer https://token.actions.githubusercontent.com --certificate-identity-regexp https://github.com/home-assistant/core/.* "${image}"; then
+      #         echo "Invalid signature!"
+      #         exit 1
+      #       fi
+      #     }
 
-          # function push_dockerhub() {
-          #   local image=${1}
-          #   local tag=${2}
+      #     # function push_dockerhub() {
+      #     #   local image=${1}
+      #     #   local tag=${2}
 
-          #   docker tag "ghcr.io/home-assistant/${image}:${tag}" "docker.io/homeassistant/${image}:${tag}"
-          #   docker push "docker.io/homeassistant/${image}:${tag}"
-          #   cosign sign --yes "docker.io/homeassistant/${image}:${tag}"
-          # }
+      #     #   docker tag "ghcr.io/home-assistant/${image}:${tag}" "docker.io/homeassistant/${image}:${tag}"
+      #     #   docker push "docker.io/homeassistant/${image}:${tag}"
+      #     #   cosign sign --yes "docker.io/homeassistant/${image}:${tag}"
+      #     # }
 
-          # Pull images from github container registry and verify signature
-          docker pull "ghcr.io/home-assistant/amd64-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/i386-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/armhf-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/armv7-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/aarch64-homeassistant:${{ needs.init.outputs.version }}"
+      #     # Pull images from github container registry and verify signature
+      #     docker pull "ghcr.io/my-smart-homes/amd64-homeassistant:${{ needs.init.outputs.version }}"
+      #     docker pull "ghcr.io/my-smart-homes/i386-homeassistant:${{ needs.init.outputs.version }}"
+      #     docker pull "ghcr.io/my-smart-homes/armhf-homeassistant:${{ needs.init.outputs.version }}"
+      #     docker pull "ghcr.io/my-smart-homes/armv7-homeassistant:${{ needs.init.outputs.version }}"
+      #     docker pull "ghcr.io/my-smart-homes/aarch64-homeassistant:${{ needs.init.outputs.version }}"
 
-          validate_image "ghcr.io/home-assistant/amd64-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/i386-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/armhf-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/armv7-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/aarch64-homeassistant:${{ needs.init.outputs.version }}"
+      #     validate_image "ghcr.io/my-smart-homes/amd64-homeassistant:${{ needs.init.outputs.version }}"
+      #     validate_image "ghcr.io/my-smart-homes/i386-homeassistant:${{ needs.init.outputs.version }}"
+      #     validate_image "ghcr.io/my-smart-homes/armhf-homeassistant:${{ needs.init.outputs.version }}"
+      #     validate_image "ghcr.io/my-smart-homes/armv7-homeassistant:${{ needs.init.outputs.version }}"
+      #     validate_image "ghcr.io/my-smart-homes/aarch64-homeassistant:${{ needs.init.outputs.version }}"
 
-          if [[ "${{ matrix.registry }}" ==  "docker.io/homeassistant" ]]; then
-            # Upload images to dockerhub
-            push_dockerhub "amd64-homeassistant" "${{ needs.init.outputs.version }}"
-            push_dockerhub "i386-homeassistant" "${{ needs.init.outputs.version }}"
-            push_dockerhub "armhf-homeassistant" "${{ needs.init.outputs.version }}"
-            push_dockerhub "armv7-homeassistant" "${{ needs.init.outputs.version }}"
-            push_dockerhub "aarch64-homeassistant" "${{ needs.init.outputs.version }}"
-          fi
+      #     if [[ "${{ matrix.registry }}" ==  "docker.io/my-smart-homes" ]]; then
+      #       # Upload images to dockerhub
+      #       push_dockerhub "amd64-homeassistant" "${{ needs.init.outputs.version }}"
+      #       push_dockerhub "i386-homeassistant" "${{ needs.init.outputs.version }}"
+      #       push_dockerhub "armhf-homeassistant" "${{ needs.init.outputs.version }}"
+      #       push_dockerhub "armv7-homeassistant" "${{ needs.init.outputs.version }}"
+      #       push_dockerhub "aarch64-homeassistant" "${{ needs.init.outputs.version }}"
+      #     fi
 
-          # Create version tag
-          create_manifest "${{ needs.init.outputs.version }}" "${{ needs.init.outputs.version }}"
+      #     # Create version tag
+      #     create_manifest "${{ needs.init.outputs.version }}" "${{ needs.init.outputs.version }}"
 
-          # Create general tags
-          if [[ "${{ needs.init.outputs.version }}" =~ d ]]; then
-            create_manifest "dev" "${{ needs.init.outputs.version }}"
-          elif [[ "${{ needs.init.outputs.version }}" =~ b ]]; then
-            create_manifest "beta" "${{ needs.init.outputs.version }}"
-            create_manifest "rc" "${{ needs.init.outputs.version }}"
-          else
-            create_manifest "stable" "${{ needs.init.outputs.version }}"
-            create_manifest "latest" "${{ needs.init.outputs.version }}"
-            create_manifest "beta" "${{ needs.init.outputs.version }}"
-            create_manifest "rc" "${{ needs.init.outputs.version }}"
+      #     # Create general tags
+      #     if [[ "${{ needs.init.outputs.version }}" =~ d ]]; then
+      #       create_manifest "dev" "${{ needs.init.outputs.version }}"
+      #     elif [[ "${{ needs.init.outputs.version }}" =~ b ]]; then
+      #       create_manifest "beta" "${{ needs.init.outputs.version }}"
+      #       create_manifest "rc" "${{ needs.init.outputs.version }}"
+      #     else
+      #       create_manifest "stable" "${{ needs.init.outputs.version }}"
+      #       create_manifest "latest" "${{ needs.init.outputs.version }}"
+      #       create_manifest "beta" "${{ needs.init.outputs.version }}"
+      #       create_manifest "rc" "${{ needs.init.outputs.version }}"
 
-            # Create series version tag (e.g. 2021.6)
-            v="${{ needs.init.outputs.version }}"
-            create_manifest "${v%.*}" "${{ needs.init.outputs.version }}"
-          fi
+      #       # Create series version tag (e.g. 2021.6)
+      #       v="${{ needs.init.outputs.version }}"
+      #       create_manifest "${v%.*}" "${{ needs.init.outputs.version }}"
+      #     fi
 
   build_python:
     name: Build PyPi package
